"""empty message

Revision ID: 015c0c8e6c6c
Revises: 
Create Date: 2019-08-22 17:11:13.706458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015c0c8e6c6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price_after_discount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price_after_discount')
    # ### end Alembic commands ###
