"""empty message

Revision ID: 7e7f88c61abd
Revises: 015c0c8e6c6c
Create Date: 2019-08-22 17:17:58.530562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e7f88c61abd'
down_revision = '015c0c8e6c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('email', sa.String(length=30), nullable=False))
    op.add_column('admin', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('admin', sa.Column('password', sa.String(length=30), nullable=False))
    op.add_column('admin', sa.Column('username', sa.String(length=30), nullable=False))
    op.drop_column('admin', 'admin_username')
    op.drop_column('admin', 'admin_id')
    op.drop_column('admin', 'admin_email')
    op.drop_column('admin', 'admin_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('admin_password', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('admin', sa.Column('admin_email', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('admin', sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('admin', sa.Column('admin_username', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('admin', 'username')
    op.drop_column('admin', 'password')
    op.drop_column('admin', 'id')
    op.drop_column('admin', 'email')
    # ### end Alembic commands ###
